---
- name: Setup the test machine
  hosts: instance
  tasks:
    - name: Create docker.sock
      raw: touch /var/run/docker.sock
      become: true
      changed_when: false
    - name: Move docker.sock from tmp
      raw: mount --move /tmp/docker_mounted.sock /var/run/docker.sock
      become: true
      changed_when: false
