---
- name: Setup the test machine
  hosts: instance-authentik
  tasks:
    - name: Create docker.sock
      raw: touch /var/run/docker.sock
      become: true
      changed_when: false

    - name: Move docker.sock from tmp
      raw: mount --move /tmp/docker_mounted.sock /var/run/docker.sock
      become: true
      changed_when: false

    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Install python requests
      pip:
        name: 
          - requests
          - docker
          - docker-compose

    - name: Install docker
      vars:
        docker_service_manage: false
      include_role:
        name: geerlingguy.docker
